--------- DATA SHARE CONSUMER ------------------------------
USE ROLE ACCOUNTADMIN

SELECT * FROM "SNOWFLAKE"."ACCOUNT_USAGE"."DATA_TRANSFER_HISTORY"

-------------- Create Access Table --------------------

CREATE OR REPLACE TABLE "TRAININGDB"."SALES"."SHARE_ACCESS" (
  SUPPL_ID STRING,
  SNOWFLAKE_ACCOUNT STRING
);

INSERT INTO "TRAININGDB"."SALES"."SHARE_ACCESS"
SELECT '5050', CURRENT_ACCOUNT()
UNION
SELECT '7560', ''
UNION
SELECT '2540', 'TEST_SHARE_ACCOUNT'

--------------- Create Secure View (Fail Version )----------------------

CREATE OR REPLACE SECURE VIEW "TRAININGDB"."PUBLIC"."SUPPLIER_VIEW_SECURE" AS
Select 
P_PARTKEY,
P_NAME, 
P_MFGR, 
P_BRAND, 
P_TYPE , 
P_SIZE , 
P_CONTAINER	, 
P_RETAILPRICE, 
P_COMMENT,
S_SUPPKEY,
PS_AVAILQTY,PS_SUPPLYCOST,
PS_COMMENT
from "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."PART" P
Join "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."PARTSUPP" PS on PS.PS_PARTKEY = P.P_PARTKEY
Join "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."SUPPLIER" S on S.S_SUPPKEY = PS.PS_SUPPKEY
join "TRAININGDB"."SALES"."SHARE_ACCESS" SA on S.S_SUPPKEY = SA.SUPPL_ID
WHERE SA.SNOWFLAKE_ACCOUNT = CURRENT_ACCOUNT()

------ Create Table As for PArts, Supplier and PARTSUP table for Pass Version ----------

SELECT * FROM "TRAININGDB"."PUBLIC"."SUPPLIER_VIEW_SECURE"
CREATE OR REPLACE TABLE  "TRAININGDB"."SALES"."SUPPLIER" AS
SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."SUPPLIER"

CREATE  OR REPLACE TABLE  "TRAININGDB"."SALES"."PARTSUPP" AS
SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."PARTSUPP"

CREATE  OR REPLACE TABLE "TRAININGDB"."SALES"."PART" AS
SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."PART"


--------------Create Secure View (Pass Version ) -------------------------

CREATE OR REPLACE SECURE VIEW "TRAININGDB"."PUBLIC"."SUPPLIER_VIEW_SECURE" AS
Select 
P_PARTKEY,
P_NAME, 
P_MFGR, 
P_BRAND, 
P_TYPE , 
P_SIZE , 
P_CONTAINER	, 
P_RETAILPRICE, 
P_COMMENT,
S_SUPPKEY,
PS_AVAILQTY,PS_SUPPLYCOST,
PS_COMMENT
from "TRAININGDB"."SALES"."PART" P
Join "TRAININGDB"."SALES"."PARTSUPP" PS on PS.PS_PARTKEY = P.P_PARTKEY
Join "TRAININGDB"."SALES"."SUPPLIER" S on S.S_SUPPKEY = PS.PS_SUPPKEY
join "TRAININGDB"."SALES"."SHARE_ACCESS" SA on S.S_SUPPKEY = SA.SUPPL_ID
WHERE SA.SNOWFLAKE_ACCOUNT = CURRENT_ACCOUNT()


---Check If our Secured View Works --------------------------
SELECT * FROM "TRAININGDB"."PUBLIC"."SUPPLIER_VIEW_SECURE"

---------- Test Secure View without loging in consumer account -----
ALTER SESSION SET SIMULATED_DATA_SHARING_CONSUMER = <your account number without quotes>

SELECT * FROM "TRAININGDB"."PUBLIC"."SUPPLIER_VIEW_SECURE"

--------------- Update Share access with newly created reader account --------------

UPDATE "TRAININGDB"."SALES"."SHARE_ACCESS"
SET SNOWFLAKE_ACCOUNT = '<Your reader account number>'
WHERE SUPPL_ID =  '7560' 

--------------------------------------------------------------------------------------